import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { releaseHistory } from "../release-info.js";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

test("release identity stays compatible with 0.1.0 upgrades and preserves user data", async () => {
  const packageJson = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
  const html = await fs.readFile(path.join(root, "public", "index.html"), "utf8");
  const renderer = await fs.readFile(path.join(root, "public", "app.js"), "utf8");
  const styles = await fs.readFile(path.join(root, "public", "styles.css"), "utf8");
  const gateway = await fs.readFile(path.join(root, "responses-gateway.js"), "utf8");
  const providerSync = await fs.readFile(path.join(root, "provider-sync.js"), "utf8");
  const updater = await fs.readFile(path.join(root, "app-updater.js"), "utf8");
  const electronMain = await fs.readFile(path.join(root, "electron", "main.mjs"), "utf8");
  const preload = await fs.readFile(path.join(root, "electron", "preload.cjs"), "utf8");
  const threadRepair = await fs.readFile(path.join(root, "thread-repair.js"), "utf8");
  const overlayHtml = await fs.readFile(path.join(root, "public", "codex-overlay.html"), "utf8");
  const overlayHelper = await fs.readFile(path.join(root, "electron", "windows-codex-window.mjs"), "utf8");
  const gatewayHost = await fs.readFile(path.join(root, "electron", "gateway-host.mjs"), "utf8");
  const codexJs = await fs.readFile(path.join(root, "codex.js"), "utf8");
  const codexActivity = await fs.readFile(path.join(root, "codex-activity.js"), "utf8");
  const diagnostics = await fs.readFile(path.join(root, "diagnostics.js"), "utf8");
  const releaseInfo = await fs.readFile(path.join(root, "release-info.js"), "utf8");
  const profilesJs = await fs.readFile(path.join(root, "profiles.js"), "utf8");
  const modelCatalog = await fs.readFile(path.join(root, "model-catalog.js"), "utf8");
  const relayTest = await fs.readFile(path.join(root, "relay-connection.js"), "utf8");
  const releaseNotes = await fs.readFile(path.join(root, "release-notes", `v${packageJson.version}.md`), "utf8");
  assert.equal(packageJson.version, "1.13.0");
  assert.equal(packageJson.author, "Guan Jingyang <guanjingyang@gmail.com>");
  assert.equal(packageJson.license, "MIT");
  assert.equal(packageJson.build.appId, "io.github.codex-galaxy.app");
  assert.equal(packageJson.build.productName, "Codex Galaxy");
  assert.equal(packageJson.build.nsis.guid, "566d1898-c777-51ee-b4e6-4cb1f476cadd");
  assert.equal(packageJson.build.nsis.perMachine, false);
  assert.equal(packageJson.build.nsis.deleteAppDataOnUninstall, false);
  assert.equal(packageJson.dependencies.koffi, "^3.1.6");
  assert.ok(packageJson.build.files.includes("responses-gateway.js"));
  assert.ok(packageJson.build.files.includes("model-catalog.js"));
  assert.ok(packageJson.build.files.includes("project-cleanup.js"));
  assert.ok(packageJson.build.files.includes("thread-repair.js"));
  assert.ok(packageJson.build.files.includes("app-updater.js"));
  assert.ok(packageJson.build.files.includes("relay-connection.js"));
  assert.ok(packageJson.build.files.includes("relay-audit.js"));
  assert.ok(packageJson.build.files.includes("relay-ranking.js"));
  assert.ok(packageJson.build.files.includes("codex-activity.js"));
  assert.ok(packageJson.build.files.includes("diagnostics.js"));
  assert.ok(packageJson.build.files.includes("release-info.js"));
  assert.ok(packageJson.build.files.includes("cli-discovery.js"));
  assert.ok(packageJson.build.files.includes("electron/windows-codex-window.mjs"));
  assert.ok(packageJson.build.files.includes("public/codex-overlay.html"));
  assert.ok(packageJson.build.files.includes("node_modules/koffi/**/*"));
  assert.match(gateway, /127\.0\.0\.1/);
  assert.match(providerSync, /record\?\.type !== "response_item" \|\| !record\.payload/);
  assert.match(providerSync, /typeof id === "string" && id\.startsWith\(idPrefix\)/);
  assert.match(providerSync, /itemType === "function_call"/);
  assert.match(providerSync, /idPrefix/);
  assert.match(providerSync, /version: 3/);
  assert.match(providerSync, /Array\.isArray\(item\.lineBackups\)/);
  assert.match(providerSync, /codex-galaxy-official-message-id-cache\.json/);
  assert.match(providerSync, /cacheStampMatches\(officialScanCache\?\.files\?\.\[cacheKey\], stat\)/);
  assert.match(providerSync, /officialScanTotalBytes/);
  assert.match(providerSync, /preserveOfficialMessageScanCacheAfterHeaderSync/);
  assert.match(electronMain, /requestSingleInstanceLock\(\)/);
  assert.match(electronMain, /second-instance/);
  assert.match(electronMain, /version: app\.getVersion\(\)/);
  assert.match(electronMain, /startCodexVersionOverlay/);
  assert.match(electronMain, /nativeWindowHandleFromBuffer/);
  assert.match(electronMain, /startUpdateChecks\(\)/);
  assert.match(electronMain, /codex-galaxy:check-update/);
  assert.match(electronMain, /codex-galaxy:install-update/);
  assert.match(electronMain, /codex-galaxy:delete-profile/);
  assert.match(electronMain, /codex-galaxy:clear-profile-key/);
  assert.match(electronMain, /codex-galaxy:test-profile/);
  assert.match(electronMain, /handoffGatewayToHost/);
  assert.match(electronMain, /stopOwnedGatewayHost/);
  assert.match(electronMain, /stopCodexDesktopSafely/);
  assert.match(electronMain, /get-diagnostic-log/);
  assert.match(electronMain, /open-diagnostic-log/);
  assert.match(electronMain, /operation-failed/);
  assert.match(electronMain, /createDiagnosticLogger/);
  assert.match(electronMain, /canContinue/);
  assert.match(electronMain, /bootstrapOfficialCodex/);
  assert.match(electronMain, /waitForCodexDesktopWindow/);
  assert.match(electronMain, /resumeThreadInCodex/);
  assert.match(electronMain, /codex:\/\/threads/);
  assert.match(electronMain, /initialLibrarySyncDone/);
  assert.match(gatewayHost, /ELECTRON_RUN_AS_NODE/);
  assert.match(gatewayHost, /gateway-host\.json/);
  assert.match(gatewayHost, /unrelated process/);
  assert.match(electronMain, /if \(profile\.runtimeMode !== "gateway"\)/);
  assert.match(codexJs, /apiRuntimeMode/);
  assert.match(codexJs, /allowUncapturedOfficial/);
  assert.match(codexJs, /setOfficialWindowsSandboxFallback/);
  assert.match(codexJs, /model_catalog_json/);
  assert.match(profilesJs, /setModelCatalog/);
  assert.match(codexActivity, /hasActiveCodexTurn/);
  assert.match(codexActivity, /latestCodexThreadId/);
  assert.match(releaseInfo, /e43ce460a8bdcfbdd5fad76979740da29639c4a5/);
  assert.match(releaseInfo, /33490869449/);
  assert.match(releaseInfo, /e3e61a5b51e6f903394302b3eeb2437c94d7d318/);
  assert.match(releaseInfo, /33505366436/);
  assert.match(releaseInfo, /94c9a78fa6b5688e90994b628666e615c727dea5/);
  assert.match(releaseInfo, /33519336408/);
  assert.match(releaseInfo, /0d69c41086b50e8c6998f0e1ee5ed68b844dc378/);
  assert.match(releaseInfo, /33596691391/);
  assert.match(releaseInfo, /c7e0034525e895bbd0f855cc5edd229098e1f938/);
  assert.match(releaseInfo, /33521136697/);
  assert.deepEqual(releaseHistory(packageJson.version)[0], {
    version: "1.13.0",
    tag: "v1.13.0",
    commit: null,
    actionsRun: null,
    url: "https://github.com/guanjingyang0015/Codex-Galaxy/releases/tag/v1.13.0",
  });
  assert.match(profilesJs, /PROFILE_SCHEMA_VERSION = 6/);
  assert.match(relayTest, /\/models/);
  assert.doesNotMatch(renderer, /profile\.current\s*\?/);
  assert.match(releaseNotes, /文档|documentation/i);
  assert.match(modelCatalog, /instructions_template: "\{\{ personality \}\}"/);
  assert.match(preload, /checkUpdate/);
  assert.match(preload, /installUpdate/);
  assert.match(preload, /onUpdateStatus/);
  assert.match(preload, /repairThread/);
  assert.match(preload, /deleteProfile/);
  assert.match(preload, /clearProfileKey/);
  assert.match(preload, /testProfile/);
  assert.match(preload, /getDiagnosticLog/);
  assert.match(preload, /openDiagnosticLog/);
  assert.match(diagnostics, /REDACTED/);
  assert.match(diagnostics, /diagnosticLogPath/);
  assert.match(diagnostics, /MAX_LOG_BYTES/);
  assert.match(diagnostics, /localTime/);
  assert.match(electronMain, /diagnoseThreadRollout/);
  assert.match(electronMain, /repairThreadRollout/);
  assert.match(threadRepair, /byte-exact/i);
  assert.match(threadRepair, /session_meta/);
  assert.match(updater, /RELEASES_LATEST_PAGE_URL/);
  assert.match(updater, /guanjingyang0015\/Codex-Galaxy\/releases\/latest/);
  assert.match(updater, /SHA-256 校验失败/);
  assert.match(overlayHtml, /Codex Galaxy/);
  assert.match(overlayHtml, /id="version"/);
  assert.match(overlayHelper, /QueryFullProcessImageNameW/);
  assert.match(overlayHelper, /SetWindowPos/);
  assert.match(html, new RegExp(`v(?:<span[^>]*>)?${packageJson.version.replaceAll(".", "\\.")}(?:</span>)?`));
  assert.doesNotMatch(html, /api-guide|relay-copy|rightapi\.ai\/register|zygtoken\.com\/register/);
  assert.doesNotMatch(html, /id="appVersionBadge"|class="app-version-badge"|id="appVersion"/);
  assert.match(html, /id="appVersionInline"/);
  assert.match(html, /id="updateBtn"/);
  assert.match(html, /id="diagnosticsBtn"/);
  assert.match(html, /id="diagnosticsDialog"/);
  assert.match(html, /tutorial-stage-tabs/);
  assert.match(html, /日常切换/);
  assert.match(html, /data-i18n="tutorial.switch.apiToApi1"/);
  assert.match(html, /id="releaseRecordVersion"/);
  assert.match(html, /id="releaseRecordVersion">v1\.13\.0</);
  assert.match(renderer, /state\.releases/);
  assert.doesNotMatch(renderer, /thread\.messages \|\| \[\]\)\.slice\(-80\)/);
  assert.match(renderer, /state\.version = String\(snapshot\.version \|\| state\.version\)/);
  assert.match(renderer, /\$\("#appVersionInline"\)\.textContent = state\.version/);
  assert.doesNotMatch(renderer, /\$\("#appVersion"\)/);
  assert.match(html, /id="relayAuditDialog"/);
  assert.match(html, /id="rankingsDialog"/);
  assert.match(renderer, /startAudit/);
  assert.match(renderer, /onAuditProgress/);
  assert.match(renderer, /getRankings/);
  assert.match(renderer, /expandPluginMarketplace/);
  assert.match(electronMain, /codex-galaxy:start-audit/);
  assert.match(electronMain, /codex-galaxy:get-rankings/);
  assert.match(renderer, /relayAuditDialog/);
  assert.match(renderer, /loadRankings/);
  assert.match(renderer, /startSavedProfileAudit/);
  assert.doesNotMatch(renderer, /batchAuditBtn|startBatchSavedAudits/);
  assert.match(electronMain, /MAX_CONCURRENT_AUDITS = 3/);
  assert.match(electronMain, /auditQueue/);
  assert.match(renderer, /audit\.scoreUnit/);
  assert.match(renderer, /audit\.expectedModel/);
  assert.doesNotMatch(electronMain, /request\?\.profileIds/);
  assert.match(electronMain, /Promise\.all/);
  assert.doesNotMatch(preload, /submitAudit|auditRelay|auditProfile/);
  assert.match(electronMain, /codex-galaxy:expand-plugin-marketplace/);
  assert.match(preload, /expandPluginMarketplace/);
  assert.doesNotMatch(html, /api-guide|relay-copy|threads-panel|PROJECT THREADS|项目继续入口/);
  assert.doesNotMatch(html, /submitRanking|audit-submit-choice|将脱敏结果提交到公共排名/);
  assert.doesNotMatch(html, /auditProfileSelect/);
  assert.match(html, /auditProgress/);
  assert.match(html, /auditCompleteDialog/);
  assert.match(html, /rankingHistory90/);
  assert.match(html, /rankingModel/);
  assert.doesNotMatch(html, /batchAuditBtn|批量检测已保存 API/);
  assert.match(html, /audit\.rubric/);
  assert.match(renderer, /<a class="ranking-item"/);
  assert.match(electronMain, /Notification/);
  assert.doesNotMatch(renderer, /bridge\.copyText\(button\.dataset\.copy\)/);
  assert.match(html, /id="languageSelect"/);
  assert.match(html, /guanjingyang@gmail\.com/);
  assert.match(renderer, /codexGalaxyLanguage/);
  assert.match(renderer, /tutorial\.stage2\.title/);
  assert.match(renderer, /selectTutorialStage/);
  assert.match(renderer, /data-tutorial-stage/);
  assert.match(renderer, /openDiagnostics/);
  assert.doesNotMatch(renderer, /Error log/);
  assert.match(renderer, /navigator\.language/);
  assert.match(styles, /html,\s*body\s*\{[^}]*overflow:\s*hidden/);
  assert.match(styles, /\.profile-list\s*\{[^}]*overflow:\s*auto/);
  assert.match(styles, /\.audit-dialog/);
  assert.match(styles, /\.rankings-dialog/);
  assert.match(styles, /\.audit-progress/);
  assert.match(styles, /\.profile-actions\s*\{[^}]*grid-column:\s*2/);
  assert.match(styles, /\.diagnostics-log\s*\{/);
  assert.doesNotMatch(styles, /\.message\.api/);
  assert.doesNotMatch(renderer, /thread\.provider\s*\?\s*"api"/);
  assert.doesNotMatch(html, /preserveOfficialLogin|插件登录兼容模式/);
  assert.doesNotMatch(renderer, /profile\.loginMode\.mixed|switching\.mixedDetail/);
});
