import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

test("release identity stays compatible with 0.1.0 upgrades and preserves user data", async () => {
  const packageJson = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
  const html = await fs.readFile(path.join(root, "public", "index.html"), "utf8");
  const renderer = await fs.readFile(path.join(root, "public", "app.js"), "utf8");
  const styles = await fs.readFile(path.join(root, "public", "styles.css"), "utf8");
  const gateway = await fs.readFile(path.join(root, "responses-gateway.js"), "utf8");
  const providerSync = await fs.readFile(path.join(root, "provider-sync.js"), "utf8");
  const updater = await fs.readFile(path.join(root, "app-updater.js"), "utf8");
  const electronMain = await fs.readFile(path.join(root, "electron", "main.mjs"), "utf8");
  const preload = await fs.readFile(path.join(root, "electron", "preload.cjs"), "utf8");
  const threadRepair = await fs.readFile(path.join(root, "thread-repair.js"), "utf8");
  const overlayHtml = await fs.readFile(path.join(root, "public", "codex-overlay.html"), "utf8");
  const overlayHelper = await fs.readFile(path.join(root, "electron", "windows-codex-window.mjs"), "utf8");
  const gatewayHost = await fs.readFile(path.join(root, "electron", "gateway-host.mjs"), "utf8");
  const codexJs = await fs.readFile(path.join(root, "codex.js"), "utf8");
  const codexActivity = await fs.readFile(path.join(root, "codex-activity.js"), "utf8");
  const releaseInfo = await fs.readFile(path.join(root, "release-info.js"), "utf8");
  const profilesJs = await fs.readFile(path.join(root, "profiles.js"), "utf8");
  const modelCatalog = await fs.readFile(path.join(root, "model-catalog.js"), "utf8");
  const relayTest = await fs.readFile(path.join(root, "relay-connection.js"), "utf8");
  const releaseNotes = await fs.readFile(path.join(root, "release-notes", "v1.9.2.md"), "utf8");
  assert.equal(packageJson.version, "1.9.2");
  assert.equal(packageJson.author, "Guan Jingyang <guanjingyang@gmail.com>");
  assert.equal(packageJson.license, "MIT");
  assert.equal(packageJson.build.appId, "io.github.codex-galaxy.app");
  assert.equal(packageJson.build.productName, "Codex Galaxy");
  assert.equal(packageJson.build.nsis.guid, "566d1898-c777-51ee-b4e6-4cb1f476cadd");
  assert.equal(packageJson.build.nsis.perMachine, false);
  assert.equal(packageJson.build.nsis.deleteAppDataOnUninstall, false);
  assert.equal(packageJson.dependencies.koffi, "^3.1.6");
  assert.ok(packageJson.build.files.includes("responses-gateway.js"));
  assert.ok(packageJson.build.files.includes("model-catalog.js"));
  assert.ok(packageJson.build.files.includes("project-cleanup.js"));
  assert.ok(packageJson.build.files.includes("thread-repair.js"));
  assert.ok(packageJson.build.files.includes("app-updater.js"));
  assert.ok(packageJson.build.files.includes("relay-connection.js"));
  assert.ok(packageJson.build.files.includes("codex-activity.js"));
  assert.ok(packageJson.build.files.includes("release-info.js"));
  assert.ok(packageJson.build.files.includes("cli-discovery.js"));
  assert.ok(packageJson.build.files.includes("electron/windows-codex-window.mjs"));
  assert.ok(packageJson.build.files.includes("public/codex-overlay.html"));
  assert.ok(packageJson.build.files.includes("node_modules/koffi/**/*"));
  assert.match(gateway, /127\.0\.0\.1/);
  assert.match(providerSync, /record\?\.type !== "response_item" \|\| !record\.payload/);
  assert.match(providerSync, /typeof id === "string" && id\.startsWith\(idPrefix\)/);
  assert.match(providerSync, /itemType === "function_call"/);
  assert.match(providerSync, /idPrefix/);
  assert.match(providerSync, /version: 3/);
  assert.match(providerSync, /Array\.isArray\(item\.lineBackups\)/);
  assert.match(providerSync, /codex-galaxy-official-message-id-cache\.json/);
  assert.match(providerSync, /cacheStampMatches\(officialScanCache\?\.files\?\.\[cacheKey\], stat\)/);
  assert.match(providerSync, /officialScanTotalBytes/);
  assert.match(providerSync, /preserveOfficialMessageScanCacheAfterHeaderSync/);
  assert.match(electronMain, /requestSingleInstanceLock\(\)/);
  assert.match(electronMain, /second-instance/);
  assert.match(electronMain, /version: app\.getVersion\(\)/);
  assert.match(electronMain, /startCodexVersionOverlay/);
  assert.match(electronMain, /nativeWindowHandleFromBuffer/);
  assert.match(electronMain, /startUpdateChecks\(\)/);
  assert.match(electronMain, /codex-galaxy:check-update/);
  assert.match(electronMain, /codex-galaxy:install-update/);
  assert.match(electronMain, /codex-galaxy:delete-profile/);
  assert.match(electronMain, /codex-galaxy:clear-profile-key/);
  assert.match(electronMain, /codex-galaxy:test-profile/);
  assert.match(electronMain, /handoffGatewayToHost/);
  assert.match(electronMain, /stopOwnedGatewayHost/);
  assert.match(electronMain, /stopCodexDesktopSafely/);
  assert.match(electronMain, /canContinue/);
  assert.match(gatewayHost, /ELECTRON_RUN_AS_NODE/);
  assert.match(gatewayHost, /gateway-host\.json/);
  assert.match(gatewayHost, /unrelated process/);
  assert.match(electronMain, /if \(profile\.runtimeMode !== "gateway"\)/);
  assert.match(codexJs, /apiRuntimeMode/);
  assert.match(codexActivity, /hasActiveCodexTurn/);
  assert.match(releaseInfo, /e43ce460a8bdcfbdd5fad76979740da29639c4a5/);
  assert.match(releaseInfo, /33490869449/);
  assert.match(profilesJs, /PROFILE_SCHEMA_VERSION = 5/);
  assert.match(relayTest, /\/models/);
  assert.doesNotMatch(renderer, /profile\.current\s*\?/);
  assert.match(releaseNotes, /多中转站管理/);
  assert.match(modelCatalog, /instructions_template: "\{\{ personality \}\}"/);
  assert.match(preload, /checkUpdate/);
  assert.match(preload, /installUpdate/);
  assert.match(preload, /onUpdateStatus/);
  assert.match(preload, /repairThread/);
  assert.match(preload, /deleteProfile/);
  assert.match(preload, /clearProfileKey/);
  assert.match(preload, /testProfile/);
  assert.match(electronMain, /diagnoseThreadRollout/);
  assert.match(electronMain, /repairThreadRollout/);
  assert.match(threadRepair, /byte-exact/i);
  assert.match(threadRepair, /session_meta/);
  assert.match(updater, /RELEASES_LATEST_PAGE_URL/);
  assert.match(updater, /guanjingyang0015\/Codex-Galaxy\/releases\/latest/);
  assert.match(updater, /SHA-256 校验失败/);
  assert.match(overlayHtml, /Codex Galaxy/);
  assert.match(overlayHtml, /id="version"/);
  assert.match(overlayHelper, /QueryFullProcessImageNameW/);
  assert.match(overlayHelper, /SetWindowPos/);
  assert.match(html, new RegExp(`v(?:<span[^>]*>)?${packageJson.version.replaceAll(".", "\\.")}(?:</span>)?`));
  assert.match(html, /https:\/\/www\.rightapi\.ai\/register\?aff=d910c1b8/);
  assert.equal(html.match(/https:\/\/www\.rightapi\.ai\/register\?aff=d910c1b8/g)?.length, 1);
  assert.doesNotMatch(html, />RightAPI|>ZYG Token|aria-label="[^"]*(?:RightAPI|ZYG Token)/);
  assert.doesNotMatch(html, /id="appVersionBadge"|class="app-version-badge"|id="appVersion"/);
  assert.match(html, /id="appVersionInline"/);
  assert.match(html, /id="updateBtn"/);
  assert.match(html, /id="releaseRecordVersion"/);
  assert.match(renderer, /state\.releases/);
  assert.match(renderer, /state\.version = String\(snapshot\.version \|\| state\.version\)/);
  assert.match(renderer, /\$\("#appVersionInline"\)\.textContent = state\.version/);
  assert.doesNotMatch(renderer, /\$\("#appVersion"\)/);
  assert.match(html, /https:\/\/api\.zygtoken\.com\/register\?aff=Z3xM/);
  assert.equal(html.match(/https:\/\/api\.zygtoken\.com\/register\?aff=Z3xM/g)?.length, 1);
  assert.match(html, /data-name="中转站 A"/);
  assert.match(html, /data-name="中转站 B"/);
  assert.match(html, /点击获取中转站链接/);
  assert.match(html, /按服务商提示完成开通/);
  assert.match(renderer, /Get relay A link/);
  assert.match(renderer, /Get relay B link/);
  assert.doesNotMatch(html, /点击复制注册链接|注册链接/);
  assert.doesNotMatch(renderer, /registration link|registration URL|注册链接|注册地址/);
  assert.match(renderer, /expandPluginMarketplace/);
  assert.match(electronMain, /codex-galaxy:expand-plugin-marketplace/);
  assert.match(preload, /expandPluginMarketplace/);
  assert.match(renderer, /bridge\.copyText\(button\.dataset\.copy\)/);
  assert.match(renderer, /查看详情/);
  assert.match(renderer, /在 Codex 中继续/);
  assert.doesNotMatch(html, /LOCAL CONTINUITY/);
  assert.match(html, /id="languageSelect"/);
  assert.match(html, /guanjingyang@gmail\.com/);
  assert.match(renderer, /codexGalaxyLanguage/);
  assert.match(renderer, /navigator\.language/);
  assert.match(styles, /html,\s*body\s*\{[^}]*overflow:\s*hidden/);
  assert.match(styles, /\.profile-list\s*\{[^}]*overflow:\s*auto/);
  assert.match(styles, /\.thread-list\s*\{[^}]*overflow:\s*auto/);
  assert.match(styles, /\.api-guide-head\s*\{[^}]*font-size:\s*13px/);
  assert.match(styles, /\.api-guide p\s*\{[^}]*font-size:\s*11px/);
  assert.match(styles, /\.relay-copy\s*\{[^}]*font-size:\s*12px/);
  assert.match(styles, /\.relay-url\s*\{[^}]*font-size:\s*10px/);
  assert.doesNotMatch(styles, /\.message\.api/);
  assert.doesNotMatch(renderer, /thread\.provider\s*\?\s*"api"/);
  assert.doesNotMatch(html, /preserveOfficialLogin|插件登录兼容模式/);
  assert.doesNotMatch(renderer, /profile\.loginMode\.mixed|switching\.mixedDetail/);
});
